name: Mobile + Release
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        storage-type: [EXTERNAL, MEDIA, OBB, DATA]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android -D officialBuild -D ${{ matrix.storage-type }} -final
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: androidBuild-${{ matrix.storage-type }}
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
  iOS:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Compile
        run: haxelib run lime build ios -D NOVIDEO -D officialBuild -final

      - name: Make Ipa
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r CodenameEngine.ipa Payload

      - name: Make Zip For Release
        run: |
           cd export/release/ios/build/Release-iphoneos
           zip CodenameEngine-iOS.zip CodenameEngine.ipa

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.zip
          if-no-files-found: error
  Releaser:
    needs: [Android, iOS]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download OBB Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild-OBB
           path: /home/runner

      - name: Move OBB File
        run: mv /home/runner/CodenameEngine-release.apk /home/runner/CodenameEngine-OBB.apk

      - name: Download DATA Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild-DATA
           path: /home/runner

      - name: Move DATA File
        run: mv /home/runner/CodenameEngine-release.apk /home/runner/CodenameEngine-DATA.apk

      - name: Download EXTERNAL Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild-EXTERNAL
           path: /home/runner

      - name: Move EXTERNAL File
        run: mv /home/runner/CodenameEngine-release.apk /home/runner/CodenameEngine-EXTERNAL.apk

      - name: Download MEDIA Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild-MEDIA
           path: /home/runner

      - name: Move MEDIA File
        run: mv /home/runner/CodenameEngine-release.apk /home/runner/CodenameEngine-MEDIA.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
           name: iOSBuild
           path: /home/runner

      - name: Publish The Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: ""
          title: ""
          files: |
            /home/runner/*.apk
            /home/runner/*.zip
